config/routes.rb
Rails.application.routes.draw do
    namespace :agenda do
        root 'assignments#index'
        resources :assignments do
            member do
                get :destroy_confirmation
            end
        end

        get '/assignments/:teacher_id/:discipline_id/:school_class_id', to: 'assignments#index_per_tscd'
        get '/assignments/:teacher_id/:discipline_id/:school_class_id', to: 'assignments#index_per_tscd'
        get '/assignments/:discipline_id/:school_class_id', to: 'assignments#index_per_tscd'
        post '/assignments/:id', to: 'assignments#update'
    end
end

app/models/agenda.rb
module Agenda
    def self.table_name_prefix
        'agenda_'
    end
end

app/models/agenda/assignment.rb
class Agenda::Assignment < ActiveRecord::Base
    belongs_to :teacher_school_class_discipline
    has_many :progresses, dependent: :destroy

    include Attachable

    validates_presence_of :title, :deadline, :wording, :teacher_school_class_discipline

    delegate :school_class, to: :teacher_school_class_discipline
    delegate :teacher, to: :teacher_school_class_discipline
    delegate :discipline, to: :teacher_school_class_discipline

    alias_method :tscd, :teacher_school_class_discipline

    # Fetches the progress for a given student.
    # If the progress doesn't exist, report it as 0.
    def progress_for(student)
        progress = progresses.find_by student: student
        progress ? progress.progress : 0
    end
end

::TeacherSchoolClassDiscipline.send(:has_many, :agenda_assignments, { class_name: 'Agenda::Assignment' })

app/models/agenda/progress.rb
class Agenda::Progress < ActiveRecord::Base
    belongs_to :student
    belongs_to :assignment

    validates_presence_of :progress, :student, :assignment
    validates_inclusion_of :progress, { in: 0..100, message: "should be included between 0 and 100%." }

    delegate :school_class, to: :assignment
    delegate :teacher, to: :assignment
    delegate :discipline, to: :assignment
end

::Student.send(:has_many, :agenda_progresses, { class_name: 'Agenda::Progress' })

app/controllers/agenda/assignments_controller.rb
class Agenda::AssignmentsController < ApplicationController
    def index
        # Required as it is not automatically loaded, so we call
        # it to make Rails load it.
        # A better solution is needed...
        Agenda::Assignment

        if current_user.roles.count > 1
            index_multirole
        elsif current_user.is_student?
            index_student
        elsif current_user.is_teacher?
            index_teacher
        elsif current_user.is_admin?
            index_admin
        elsif current_user.is_parent?
            index_parent
        else
            raise Pundit::NotAuthorizedError
        end
    end

    def new
        @agenda_assignment = Agenda::Assignment.new
        authorize(@agenda_assignment)
    end

    def create
        respond_to do |format|
            format.html do
                @agenda_assignment = Agenda::Assignment.new(permitted_params)
                authorize(@agenda_assignment)

                if @agenda_assignment.save
                    redirect_to @agenda_assignment, notice: 'Assignment succesfully created'
                else
                    render action: :new
                end
            end
            format.json do
                if current_user.is_teacher?
                    data = create_teacher_json
                    if data[:error]
                        render json: data, status: :internal_server_error
                    else
                        render json: data
                    end
                else
                    authorize(Agenda::Assignment)

                    render json: { error: "You are not allowed to access this data." }, status: :forbidden
                end
            end
        end
    end

    def edit
        @agenda_assignment = Agenda::Assignment.find(params[:id])
        authorize(@agenda_assignment)
    end

    def update
        @agenda_assignment = Agenda::Assignment.find(params[:id])
        authorize(@agenda_assignment)

        respond_to do |format|
            format.html do
                if request.referer == agenda_assignment_url(@agenda_assignment) &&
                    current_user.is_student? &&
                    current_user.as_student.teacher_school_class_disciplines.map { |tscd| tscd.agenda_assignments.include? @agenda_assignment }.include?(true)
                    p = @agenda_assignment.progresses.find_by(student: current_user.as_student)
                    if p.nil?
                        p = Agenda::Progress.new(student: current_user.as_student,
                                                   assignment: @agenda_assignment,
                                                   progress: params[:agenda_assignment][:progress])
                        if p.save
                            redirect_to @agenda_assignment, notice: 'Progression succesfully updated'
                        else
                            redirect_to @agenda_assignment, notice: p.errors.full_messages.join("\n")
                        end
                    elsif p.update_attributes(progress: params[:agenda_assignment][:progress])
                        redirect_to @agenda_assignment, notice: 'Progression succesfully updated'
                    else
                        redirect_to @agenda_assignment, notice: p.errors.full_messages.join("\n")
                    end
                elsif @agenda_assignment.update(permitted_params)
                    redirect_to @agenda_assignment, notice: 'Assignment succesfully updated'
                else
                    render action: :edit
                end
            end
            format.json do
                if current_user.roles.count > 1
                    if params[:as].nil?
                        render json: { error: "You have multiple roles. Use a 'as' parameter to precise type of response." }, status: :bad_request
                    elsif !current_user.roles.map { |role| role.role_type.downcase }.include?(params[:as])
                        render json: { error: "You do not have that role." }, status: :forbidden
                    else
                        data = send("update_#{params[:as]}_json")
                        if data[:error]
                            render json: data, status: :internal_server_error
                        else
                            render json: data
                        end
                    end
                elsif current_user.is_student?
                    data = update_student_json
                    if data[:error]
                        render json: data, status: :internal_server_error
                    else
                        render json: data
                    end
                elsif current_user.is_teacher?
                    data = update_teacher_json
                    if data[:error]
                        render json: data, status: :internal_server_error
                    else
                        render json: data
                    end
                else
                    render json: { error: "You are not allowed to access this data." }, status: :forbidden
                end
            end
        end
    end

    def show
        @agenda_assignment = Agenda::Assignment.find(params[:id])
        authorize(@agenda_assignment)

        respond_to do |format|
            format.html {}
            format.json do
                if current_user.roles.count > 1
                    if params[:as].nil?
                        render json: { error: "You have multiple roles. Use a 'as' parameter to precise type of response." }, status: :bad_request
                    elsif !current_user.roles.map { |role| role.role_type.downcase }.include?(params[:as])
                        render json: { error: "You do not have that role." }, status: :forbidden
                    else
                        data = send("show_#{params[:as]}_json")
                        if data[:error]
                            render json: data, status: :internal_server_error
                        else
                            render json: data
                        end
                    end
                elsif current_user.is_teacher?
                    data = show_teacher_json
                    if data[:error]
                        render json: data, status: :internal_server_error
                    else
                        render json: data
                    end
                elsif current_user.is_student?
                    data = show_student_json
                    if data[:error]
                        render json: data, status: :internal_server_error
                    else
                        render json: data
                    end
                else
                    render json: { error: "You are not allowed to access this data." }, status: :forbidden
                end
            end
        end
    end

    def destroy
        @agenda_assignment = Agenda::Assignment.find(params[:id])
        authorize(@agenda_assignment)
        @agenda_assignment.destroy
        redirect_to agenda_root_path
    end

    def destroy_confirmation
        @agenda_assignment = Agenda::Assignment.find(params[:id])
        authorize(@agenda_assignment)
    end

    def index_per_tscd
        teacher_id = params[:teacher_id] || (current_user.as_teacher.id if current_user.is_teacher?)

        tscd = TeacherSchoolClassDiscipline.find_by(teacher_id: teacher_id,
                                                       discipline_id: params[:discipline_id],
                                                       school_class_id: params[:school_class_id])
        authorize(tscd)

        # Required as it is not automatically loaded, so we call
        # it to make Rails load it.
        # A better solution is needed...
        Agenda::Assignment

        respond_to do |format|
            format.html { @agenda_assignments = tscd.agenda_assignments.group_by { |e| e.deadline } }
            format.json {
                data = tscd.agenda_assignments.map do |e|
                    {
                        id: e.id,
                        title: e.title,
                        deadline: e.deadline,
                        duetime: e.duetime ? e.duetime.utc.to_s(:time) : nil,
                        discipline: {
                            id: e.discipline.id,
                            name: e.discipline.name
                        },
                        school_class: {
                            id: e.school_class.id,
                            name: e.school_class.name
                        }
                    }
                end
                render json: data
            }
        end
    end

    # This method allows to raise a better exception for a missing role method
    def method_missing(m, *args, &block)
        if /index_(?<role_name>\w+)/ =~ m.to_s ||
            /get_(?<role_name>\w+)_data/ =~ m.to_s ||
            /update_(?<role_name>\w+)_json/ =~ m.to_s
            if request.headers['Content-Type'] == "application/json"
                return { error: "The role #{role_name} doesn't exist or isn't managed by this controller" }
            else
                raise "The role #{role_name} doesn't exist or isn't managed by this controller"
            end
        else
            super
        end
    end

    private
    def permitted_params(key = :agenda_assignment)
        params.require(key).permit(:wording,
                                   :title,
                                   :deadline,
                                   :duetime,
                                   :teacher_school_class_discipline_id,
                                   attachments_attributes: Attachment::PermittedParams
                                   )
    end

    # Get the raw data for a student
    def get_student_data(data_mapping = nil)
        data = policy_scope(TeacherSchoolClassDiscipline)

app/views/agenda/assignments/_admin_row.html.haml
- data.each do |teacher|
    %h3= teacher.full_name
    .uk-margin-large-left
        - teacher.disciplines.each do |discipline|
            %h4= discipline.name
            .cl-box-list
                - discipline.school_classes.each do |cls|
                    = link_to agenda_path(teacher.id, discipline.id, cls.id), class: 'uk-panel uk-panel-box' do
                        %strong= cls.name
                        %span.uk-float-right
                            %span.uk-text-muted #{cls.assignment_count} assignment(s)
                            %i.uk-icon-chevron-right.uk-margin-left

app/views/agenda/assignments/_form.html.haml
= nested_form_for agenda_assignment, html: { class: 'uk-form uk-form-horizontal' } do |f|
    = f.auto_input :title
    = f.auto_input :wording, field_method: :text_area, field: {rows: 5}
    .uk-form-row
        = f.label :discipline, class: "uk-form-label"
        .uk-form-controls
            - if current_user.is_teacher?
                = f.select(:teacher_school_class_discipline_id,
                current_user.as_teacher.tscd.map { |tscd| [ tscd.school_class_discipline_name, tscd.id]}, { include_blank: false }, { class: "uk-width-1-1" })
            - elsif current_user.is_admin?
                = f.select(:teacher_school_class_discipline_id,
                policy_scope(TeacherSchoolClassDiscipline).map { |tscd| [ "#{tscd.teacher.full_name} - #{tscd.school_class.name} - #{tscd.discipline.name}", tscd.id]}, { include_blank: false }, { class: "uk-width-1-1" })
    = f.auto_input :deadline, field_method: :date
    .uk-form-row
        = label_tag do
            = check_box_tag :add_duetime
            Check if you want to add a due time to this assignment
    = f.auto_input :duetime, field_method: :time, hide: true
    = render partial: 'attachments/form', object: f, as: :f
    = f.submit class: 'uk-button uk-button-success uk-align-right uk-margin-top'

app/views/agenda/assignments/_row.html.haml
.uk-panel.uk-panel-box
    .uk-panel-title= link_to assignment.title, assignment
    .uk-panel-meta
        %i.uk-icon-mortar-board
        = assignment.teacher.full_name
        %i.uk-icon-calendar.uk-margin-left
        = l(assignment.deadline)
        - if assignment.duetime
            = assignment.duetime.localtime.to_s(:time)
    - if current_user.is_student? && current_user.as_student.teacher_school_class_disciplines.map { |tscd| tscd.agenda_assignments.include? assignment }.include?(true)
        - assignment.progress_for(current_user.as_student).tap do |progress|
            %div{class: 'uk-progress uk-progress-mini' + (progress >= 100 ? ' uk-progress-success' : '')}
                .uk-progress-bar{style: "width: #{progress}%;"}

app/views/agenda/assignments/_student_row.html.haml
- data.each do |date, assignments|
    %h3= l(date)
    .cl-box-list
        = render partial: 'row', collection: assignments, as: :assignment
- if data.values.count == 0
    %em No assignment

app/views/agenda/assignments/_teacher_row.html.haml
- data.each do |discipline|
    %h3= discipline.name
    .cl-box-list
        - discipline.school_classes.each do |cls|
            = link_to agenda_path(current_user.as_teacher.id, discipline.id, cls.id), class: 'uk-panel uk-panel-box' do
                %strong= cls.name
                %span.uk-float-right
                    %span.uk-text-muted #{cls.assignment_count} assignment(s)
                    %i.uk-icon-chevron-right.uk-margin-left

app/views/agenda/assignments/destroy_confirmation.html.haml
- title! "Assignment"

%ul.uk-breadcrumb
    %li= link_to "Home", root_path
    %li= link_to "Agenda", agenda_root_path
    %li= link_to "Assignment", agenda_assignment_path(@agenda_assignment)
    %li
        %span.uk-active Delete

%p
    Are you sure you want to delete this assignment?
    %br
    %em
        %i.uk-icon-warning
        This action is permanent.
    = link_to "Back to this assignment", agenda_assignment_path(@agenda_assignment), class: "uk-align-right uk-button uk-button-danger"
    = link_to "Delete this assignment", agenda_assignment_path(@agenda_assignment), method: :delete, class: "uk-align-right uk-button uk-button-success"

- sidebar! do |sidebar|
    = sidebar.link "View this assignment", agenda_assignment_path(@agenda_assignment), icon: "eye" if policy(@agenda_assignment).show?

app/views/agenda/assignments/edit.html.haml
- title! "Edit assignment"

%ul.uk-breadcrumb
    %li= link_to "Home", root_path
    %li= link_to "Agenda", agenda_root_path
    %li= link_to "Assignment", agenda_assignment_path(@agenda_assignment)
    %li
        %span.uk-active Edit

= render partial: 'form', object: @agenda_assignment, as: :agenda_assignment

- sidebar! do |sidebar|
    = sidebar.link "View this assignment", agenda_assignment_path(@agenda_assignment), icon: "eye" if policy(@agenda_assignment).show?

app/views/agenda/assignments/index.html.haml
= title! "Assignments"

%ul.uk-breadcrumb
    %li= link_to "Home", root_path
    %li
        %span.uk-active Agenda

%ul.uk-tab{"data-uk-tab" => "{connect:'#tab-contents'}"}
    - is_first = true
    - @data.each_key do |role|
        - if is_first
            %li.uk-active= link_to role.capitalize, '#'
            - is_first = false
        - else
            %li= link_to role.capitalize, '#'
%ul#tab-contents.uk-switcher.uk-margin
    - @data.each_key do |role|
        %li
            = render partial: "#{role}_row", object: @data[role], as: :data

= sidebar! do |sidebar|
    = sidebar.link "Create an assignment", new_agenda_assignment_path, icon: "plus" if policy(Agenda::Assignment).create?

app/views/agenda/assignments/index_admin.html.haml
= title! "Assignments"

%ul.uk-breadcrumb
    %li= link_to "Home", root_path
    %li
        %span.uk-active Agenda

= render partial: "admin_row", object: @data, as: :data

= sidebar! do |sidebar|
    = sidebar.link "Create an assignment", new_agenda_assignment_path, icon: "plus" if policy(Agenda::Assignment).create?

app/views/agenda/assignments/index_per_tscd.html.haml
= title! "Assignments"

%ul.uk-breadcrumb
    %li= link_to "Home", root_path
    %li= link_to "Agenda", agenda_root_path
    %li
        %span.uk-active Assignments

- @agenda_assignments.each do |date, assignments|
    %h3= l(date)
    .cl-box-list
        = render partial: 'row', collection: assignments, as: :assignment
- if @agenda_assignments.count == 0
    %em No assignment

= sidebar! do |sidebar|
    = sidebar.link "Create an assignment", new_agenda_assignment_path, icon: "plus" if policy(Agenda::Assignment).create?

app/views/agenda/assignments/index_student.html.haml
= title! "Assignments"

%ul.uk-breadcrumb
    %li= link_to "Home", root_path
    %li
        %span.uk-active Agenda

= render partial: "student_row", object: @data, as: :data

app/views/agenda/assignments/index_teacher.html.haml
- title! 'Assignments'

%ul.uk-breadcrumb
    %li= link_to "Home", root_path
    %li
        %span.uk-active Agenda

= render partial: "teacher_row", object: @data, as: :data

= sidebar! do |sidebar|
    = sidebar.link "Create an assignment", new_agenda_assignment_path, icon: "plus" if policy(Agenda::Assignment).create?

app/views/agenda/assignments/new.html.haml
- title! "Create a new assignment"

%ul.uk-breadcrumb
    %li= link_to "Home", root_path
    %li= link_to "Agenda", agenda_root_path
    %li
        %span.uk-active New

= render partial: 'form', object: @agenda_assignment, as: :agenda_assignment

- sidebar! do |sidebar|
    = sidebar.link "View all assignments", agenda_assignments_path, icon: "eye" if policy(Agenda::Assignment).index?

app/views/agenda/assignments/show.html.haml
- title! "Assignment"

%ul.uk-breadcrumb
    %li= link_to "Home", root_path
    %li= link_to "Agenda", agenda_root_path
    %li
        %span.uk-active Assignment

.uk-panel.uk-panel-box
    %h2 #{@agenda_assignment.title}
    %br
    = @agenda_assignment.wording
%p
    Due date is
    %strong= l(@agenda_assignment.deadline)
    = @agenda_assignment.duetime.localtime.to_s(:time) unless @agenda_assignment.duetime.nil?
%p
    Given
    - if !current_user.is_teacher? || current_user.as_teacher != @agenda_assignment.teacher
        by
        %strong #{@agenda_assignment.teacher.full_name}
    for the
    %strong #{@agenda_assignment.discipline.name}
    discipline
    - if !current_user.is_student? || current_user.as_student.school_class != @agenda_assignment.school_class
        of class
        %strong #{@agenda_assignment.school_class.name}

- if current_user.is_student? && current_user.as_student.teacher_school_class_disciplines.map { |tscd| tscd.agenda_assignments.include? @agenda_assignment }.include?(true)
    %h4 Progression: #{@agenda_assignment.progress_for(current_user.as_student)}%
    #progress-slider
    %br
    = form_for @agenda_assignment do |f|
        = f.auto_input :progress, field_method: :number, hide: true, field: { min: 0, max: 100, value: @agenda_assignment.progress_for(current_user.as_student) }
        = f.submit "Submit progression", id: "progress-submission", class: "uk-button uk-button-default uk-align-right", disabled: true

= render partial: 'attachments/index', locals: { attachments: @agenda_assignment.attachments }

- sidebar! do |sidebar|
    = sidebar.link "View all assignments", agenda_assignments_path, icon: "eye" if policy(Agenda::Assignment).index?
    = sidebar.link "Create a new assignment", new_agenda_assignment_path, icon: "plus" if policy(Agenda::Assignment).create?
    = sidebar.link "Edit this assignment", edit_agenda_assignment_path(@agenda_assignment), icon: "edit" if policy(@agenda_assignment).edit?
    = sidebar.link "Delete this assignment", destroy_confirmation_agenda_assignment_path(@agenda_assignment), icon: "trash-o" if policy(@agenda_assignment).destroy?